import os
import time
import google.generativeai as genai
from typing import Optional

# ================== CONFIG ==================
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError("❌ GEMINI_API_KEY environment variable is required")

GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash-lite")  # or gemini-2.5-flash

RETRIES = int(os.environ.get("GEN_RETRIES", "5"))
RETRY_BACKOFF = float(os.environ.get("GEN_RETRY_BACKOFF", "2.0"))
TIMEOUT_SECONDS = int(os.environ.get("GEN_TIMEOUT", "120"))

genai.configure(api_key=GEMINI_API_KEY)

def generate_answer(
        prompt: str,
        max_tokens: int = 1024,
        temperature: float = 0.1,
) -> str:
    model = genai.GenerativeModel(GEMINI_MODEL)

    generation_config = genai.GenerationConfig(
        temperature=temperature,
        max_output_tokens=max_tokens,
        top_p=0.95,
    )

    for attempt in range(1, RETRIES + 1):
        try:
            response = model.generate_content(
                prompt,
                generation_config=generation_config,
                request_options={"timeout": TIMEOUT_SECONDS},
            )

            # Safety block handling
            if response.candidates is None or len(response.candidates) == 0:
                raise ValueError("Gemini blocked the response (safety/filter)")

            # === SAFE TEXT EXTRACTION (fixes empty response crash) ===
            text_parts = []
            for candidate in response.candidates:
                if candidate.content and candidate.content.parts:
                    for part in candidate.content.parts:
                        if part.text:
                            text_parts.append(part.text)

            text = "".join(text_parts).strip()

            # If still empty (very cautious model), return fallback
            if not text:
                return "No answer generated by the model."

            return text

        except Exception as e:
            if attempt == RETRIES:
                raise RuntimeError(f"Gemini generation failed after {RETRIES} attempts: {str(e)}") from e

            print(f"Gemini attempt {attempt} failed: {e} → retrying in {RETRY_BACKOFF * attempt}s...")
            time.sleep(RETRY_BACKOFF * attempt)

    raise RuntimeError("Unreachable")
